CREATE DATABASE IF NOT EXISTS authdb;
CREATE DATABASE IF NOT EXISTS balancedb;

CREATE USER IF NOT EXISTS 'wws'@'%' IDENTIFIED BY 'wws_password';
GRANT ALL PRIVILEGES ON authdb.* TO 'wws'@'%';
GRANT ALL PRIVILEGES ON balancedb.* TO 'wws'@'%';
FLUSH PRIVILEGES;